name: Deploy to GCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Cleanup Sensitive Files
        run: |
          rm -f *.json
          rm -rf .git .github

      - name: Deploy via gsutil
        run: |
          # 1. Clear existing bucket content (ignoring error if empty)
          gsutil -m rm -rf "gs://${{ secrets.GCP_BUCKET_NAME }}/**" || true
          
          # 2. Upload all files from current directory
          gsutil -m cp -r . "gs://${{ secrets.GCP_BUCKET_NAME }}"
          
      - name: Set Cache-Control
        run: |
          gsutil setmeta -h "Cache-Control:public, max-age=60" "gs://${{ secrets.GCP_BUCKET_NAME }}/index.html"
          gsutil -m setmeta -h "Cache-Control:public, max-age=60" "gs://${{ secrets.GCP_BUCKET_NAME }}/**/*.css"
          gsutil -m setmeta -h "Cache-Control:public, max-age=60" "gs://${{ secrets.GCP_BUCKET_NAME }}/**/*.js"
